---
name: Qwiet pre-zero Demo

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: elangosenthilnathan/QwietTemplate@main
      with:
        shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        verbose: true
        strict: false
        wait: true
        importGitHub: false
